/* Main.c file generated by New Project wizard
 *
 * Created:   jue may 15 2014
 * Processor: PIC18F4550
 * Compiler:  CCS for PIC
 */
 
#include <18F4550.h>
#fuses XT,NOWDT,NOPROTECT
#use delay(clock=4000000)
#use standard_io(A)
#use standard_io(B)
                  /*delay_ms(); es para retardar una instrucción*/
void main(void)
{
   
   output_high(PIN_D2);
   output_high(PIN_D3);
   output_high(PIN_D4);
   output_high(PIN_D5);
   delay_ms(400);
   output_low(PIN_D2);
   output_low(PIN_D3);
   output_low(PIN_D4);
   output_low(PIN_D5);
   
   while(TRUE)
   {
   
   output_low(PIN_D0);     //LOS MOTORES DE LLENADO Y ACTIVADO SE DESACTIVAN
   output_low(PIN_D1);     //EVITANDO EL ACTIVADO REPENTINO POR PARTE DEL PIC.

   //INICIO DEL NIVEL 1
   nivel1:
   
      if(input(PIN_B0)==TRUE)       //SI SE ACTIVA EL BOTON DEL NIVEL 2, SE EJECUTAN LAS DEMÁS SENTENCIAS:
   {
      output_low(PIN_D2);                                    //SE ACTIVA LA LUZ DEL NIVEL 2
      output_low(PIN_D3);                                   //SE DESACTIVAN LAS DEMÁS LUCES.
      output_low(PIN_D4);
      output_high(PIN_D5);
      delay_ms(700);                                        //SE RETRASA 700ms Y SE PROCEDE A, APAGAR LA LUZ DEL NIVEL 2
      output_low(PIN_D5);                                   //SE RETRASA 1s MÁS ANTES DE EVALUAR LOS SENSORES.
      delay_ms(500);
      
      if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)     //SI NO HAY INSTRUCCIONES DE CAMBIO DE NIVEL SE CONTINUA,
      {
                                                                                //DE LO CONTRARIO, SE PROCEDE A REINICIAR CON EL NIVEL
         goto nivel1;                                                           //ESPECIFICADO CON EL BOTON CORRESPONDIENTE.
      }
      
      subnivel1:                                            //ETIQUETA PARA ACCEDER CUANDO SE LE NECESITE APARTIR DE ESTA LINEA.
      if(input(PIN_B4)==FALSE)                              //SI NO HAY NADA EN EL SENSOR 2, SE PROCEDE A EJECUTAR LAS SIG. INSTRUCCIONES.
      {
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN.
         {
            while((input(PIN_B4) || input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIOS DE NIVEL...
            {                                        //... O SE ENCIENDE EL SENSOR DEL NIVEL 2, BUCLE, HASTA QUE SENSOR DE NIVEL 2 SE ACTIVE.
               output_high(PIN_D0);                         //MIENTRAS NO EXISTA CAMBIO DE NIVEL, SE EMPIEZA A LLENAR EL RECIPIENTE
               output_low(PIN_D1);                          //RECORDAR QUE C7=LLENADO; AQUI SE ENCIENDE EL MOTOR DE LLENADO
                                                           //RECORDAR QUE C6=VACIADO; AQUI SE APAGA EL MOTOR DE VACIADO.

               if(input(PIN_B4)==TRUE)
               {
                  output_high(PIN_D5);
               }
               else
               {
                  output_low(PIN_D5);
               }
   
               if(input(PIN_B5)==TRUE)
               {
                  output_high(PIN_D4);
               }
               else
               {
                  output_low(PIN_D4);
               }
               
               if(input(PIN_B6)==TRUE)
               {
                  output_high(PIN_D3);
               }
               else
               {
                  output_low(PIN_D3);
               }
   
               if(input(PIN_B7)==TRUE)
               {
                  output_high(PIN_D2);
               }
               else
               {
                  output_low(PIN_D2);
               }

            }
            
            if(input(PIN_B4)==TRUE)
            {
               output_high(PIN_D5);
            }
            else
            {
               output_low(PIN_D5);
            }

            if(input(PIN_B5)==TRUE)
            {
               output_high(PIN_D4);
            }
            else
            {
               output_low(PIN_D4);
            }
            
            if(input(PIN_B6)==TRUE)
            {
               output_high(PIN_D3);
            }
            else
            {
               output_low(PIN_D3);
            }

            if(input(PIN_B7)==TRUE)
            {
               output_high(PIN_D2);
            }
            else
            {
               output_low(PIN_D2);
            }
            
            output_low(PIN_D0);                             //SE SALIÓ DEL BUCLE ANTERIOR, ENTONCES SE PROCEDE A, APAGAR LOS MOTORES
            output_low(PIN_D1);                             //Y SE REGRESA AL NIVEL 1. CON ESTO SE VUELVEN A PEDIR LOS DATOS DE NIVEL.
            goto nivel1;
            
         }
         else
         {
            goto nivel1;
         }
      }
      
   if((input(PIN_B5) || input(PIN_B6) || input(PIN_B7))==TRUE)            //SI HAY AGUA EN LOS NIVELES 3 Y 4, LA CONDICIÓN SE CUMPLE, SINO SE VA AL ELSE.
   {
      while((input(PIN_B4) || input(PIN_B5) || input(PIN_B6) || input(PIN_B7))==TRUE)  //SI HAY AGUA EN LOS NIVELES 3, 4 Y 5, SE CUMPLE LA...
      {                                                                                //... CONDICIÓN Y SE PROCEDE A VACIAR EL TANQUE.
         output_low(PIN_D0);                             //RECORDAR QUE C7=LLENADO; AQUI SE APAGA EL MOTOR DE LLENADO
         output_high(PIN_D1);                            //RECORDAR QUE C6=VACIADO; AQUI SE ENCIENDE EL MOTOR DE VACIADO.
         
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI SE SOLICITA CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN
         {
                                                                       //PARA LA CUAL SE EJECUTA goto nivel1, Y SE VUELVE A EVALUAR LOS NIVELES.
            goto nivel1;                                               //REGRESA A LA ETIQUETA DE nivel1, (SE SOBREENTIENDE).
         }
         
         if(input(PIN_B4)==TRUE)
         {
            output_high(PIN_D5);
         }
         else
         {
            output_low(PIN_D5);
         }

         if(input(PIN_B5)==TRUE)
         {
            output_high(PIN_D4);
         }
         else
         {
            output_low(PIN_D4);
         }

         if(input(PIN_B6)==TRUE)
         {
         output_high(PIN_D3);
         }
         else
         {
            output_low(PIN_D3);
         }

         if(input(PIN_B7)==TRUE)
         {
            output_high(PIN_D2);
         }
         else
         {
            output_low(PIN_D2);
         }
      }

      if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI SE SOLICITA CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN
      {
                                                                                  //PARA LA CUAL SE EJECUTA goto nivel1, Y SE VUELVE A EVALUAR LOS NIVELES.
         goto nivel1;                                                               //REGRESA A LA ETIQUETA DE nivel1, (SE SOBREENTIENDE).
      }

      if(input(PIN_B4)==TRUE)
      {
         output_high(PIN_D5);
      }
      else
      {
         output_low(PIN_D5);
      }

      if(input(PIN_B5)==TRUE)
      {
         output_high(PIN_D4);
      }
      else
      {
         output_low(PIN_D4);
      }

      if(input(PIN_B6)==TRUE)
      {
         output_high(PIN_D3);
      }
      else
      {
         output_low(PIN_D3);
      }

      if(input(PIN_B7)==TRUE)
      {
         output_high(PIN_D2);
      }
      else
      {
         output_low(PIN_D2);
      }

      goto subnivel1;
   }

   if(input(PIN_B5)==FALSE)                                                       //SI SE CUMPLE LA CONDICIÓN DE QUE EL NIVEL 2 (EL SENSOR DEL NIVEL 2) SEA FALSO, SE
   {                                                                              //EJECUTA LAS SIGUIENTES INSTRUCCIONES CON EVALUACIONES:
      if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI HAY CAMBIO DE NIVELES, SE CUMPLE LA CONDICIÓN
      {
                                                      //Y SE PROCEDE A EJECUTAR LA SIGUIENTE INSTRUCCIÓN
         goto nivel1;                                 //IR AL nivel1 CON LA INSTRUCCIÓN goto nivel1.
      }
      else                                            //SI NO SE CUMPLIÓ, SE PROCEDE A REALIZAR LO QUE DICE EL else
      {
         goto subnivel1;                              //IR AL subnivel2, CON EL FIN DE EVALUAR NUEVAMENTE EL SENSOR DOS
      }                                               //DEBIDO A QUE EL SE REQUIERE LLEGAR AL NIVEL 2 (SENSOR DEL NIVEL 2 [PIN_B5]).
   }
   }
   //FIN DEL NIVEL 1


   //INICIO DEL NIVEL 2
   nivel2:
   if(input(PIN_B1)==TRUE)       //SI SE ACTIVA EL BOTON DEL NIVEL 2, SE EJECUTAN LAS DEMÁS SENTENCIAS:
   {
      output_low(PIN_D2);                                    //SE ACTIVA LA LUZ DEL NIVEL 2
      output_low(PIN_D3);                                   //SE DESACTIVAN LAS DEMÁS LUCES.
      output_high(PIN_D4);
      output_low(PIN_D5);
      delay_ms(700);                                        //SE RETRASA 700ms Y SE PROCEDE A, APAGAR LA LUZ DEL NIVEL 2
      output_low(PIN_D4);                                   //SE RETRASA 1s MÁS ANTES DE EVALUAR LOS SENSORES.
      delay_ms(500);
      
      if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)     //SI NO HAY INSTRUCCIONES DE CAMBIO DE NIVEL SE CONTINUA,
      {
                                                                                //DE LO CONTRARIO, SE PROCEDE A REINICIAR CON EL NIVEL
         goto nivel1;                                                           //ESPECIFICADO CON EL BOTON CORRESPONDIENTE.
      }
      
      subnivel2:                                            //ETIQUETA PARA ACCEDER CUANDO SE LE NECESITE APARTIR DE ESTA LINEA.
      if(input(PIN_B5)==FALSE)                              //SI NO HAY NADA EN EL SENSOR 2, SE PROCEDE A EJECUTAR LAS SIG. INSTRUCCIONES.
      {
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN.
         {
            while((input(PIN_B5) || input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIOS DE NIVEL...
            {
                                                            //... O SE ENCIENDE EL SENSOR DEL NIVEL 2, BUCLE, HASTA QUE SENSOR DE NIVEL 2 SE ACTIVE.
               output_high(PIN_D0);                         //MIENTRAS NO EXISTA CAMBIO DE NIVEL, SE EMPIEZA A LLENAR EL RECIPIENTE
               output_low(PIN_D1);                          //RECORDAR QUE C7=LLENADO; AQUI SE ENCIENDE EL MOTOR DE LLENADO
                                                            //RECORDAR QUE C6=VACIADO; AQUI SE APAGA EL MOTOR DE VACIADO.
               if(input(PIN_B4)==TRUE)
               {
                  output_high(PIN_D5);
               }
               else
               {
                  output_low(PIN_D5);
               }
   
               if(input(PIN_B5)==TRUE)
               {
                  output_high(PIN_D4);
               }
               else
               {
                  output_low(PIN_D4);
               }
               
               if(input(PIN_B6)==TRUE)
               {
                  output_high(PIN_D3);
               }
               else
               {
                  output_low(PIN_D3);
               }
   
               if(input(PIN_B7)==TRUE)
               {
                  output_high(PIN_D2);
               }
               else
               {
                  output_low(PIN_D2);
               }

            }
            
            if(input(PIN_B4)==TRUE)
            {
               output_high(PIN_D5);
            }
            else
            {
               output_low(PIN_D5);
            }

            if(input(PIN_B5)==TRUE)
            {
               output_high(PIN_D4);
            }
            else
            {
               output_low(PIN_D4);
            }
            
            if(input(PIN_B6)==TRUE)
            {
               output_high(PIN_D3);
            }
            else
            {
               output_low(PIN_D3);
            }

            if(input(PIN_B7)==TRUE)
            {
               output_high(PIN_D2);
            }
            else
            {
               output_low(PIN_D2);
            }
            
            output_low(PIN_D0);                             //SE SALIÓ DEL BUCLE ANTERIOR, ENTONCES SE PROCEDE A, APAGAR LOS MOTORES
            output_low(PIN_D1);                             //Y SE REGRESA AL NIVEL 1. CON ESTO SE VUELVEN A PEDIR LOS DATOS DE NIVEL.
            goto nivel1;
            
         }
         else
         {
            goto nivel1;
         }
      }
      
   if((input(PIN_B6) || input(PIN_B7))==TRUE)            //SI HAY AGUA EN LOS NIVELES 3 Y 4, LA CONDICIÓN SE CUMPLE, SINO SE VA AL ELSE.
   {
      while((input(PIN_B5) || input(PIN_B6) || input(PIN_B7))==TRUE)  //SI HAY AGUA EN LOS NIVELES 3, 4 Y 5, SE CUMPLE LA...
      {                                                                                //... CONDICIÓN Y SE PROCEDE A VACIAR EL TANQUE.
         output_low(PIN_D0);                             //RECORDAR QUE C7=LLENADO; AQUI SE APAGA EL MOTOR DE LLENADO
         output_high(PIN_D1);                            //RECORDAR QUE C6=VACIADO; AQUI SE ENCIENDE EL MOTOR DE VACIADO.
  
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI SE SOLICITA CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN
         {
                                                                 //PARA LA CUAL SE EJECUTA goto nivel1, Y SE VUELVE A EVALUAR LOS NIVELES.
            goto nivel1;                                                               //REGRESA A LA ETIQUETA DE nivel1, (SE SOBREENTIENDE).
         }

         if(input(PIN_B4)==TRUE)
         {
            output_high(PIN_D5);
         }
         else
         {
            output_low(PIN_D5);
         }
   
         if(input(PIN_B5)==TRUE)
         {
            output_high(PIN_D4);
         }
         else
         {
            output_low(PIN_D4);
         }
             
         if(input(PIN_B6)==TRUE)
         {
            output_high(PIN_D3);
         }
         else
         {
            output_low(PIN_D3);
         }
   
         if(input(PIN_B7)==TRUE)
         {
            output_high(PIN_D2);
         }
         else
         {
            output_low(PIN_D2);
         }

      }

      if(input(PIN_B4)==TRUE)
      {
         output_high(PIN_D5);
      }
      else
      {
         output_low(PIN_D5);
      }

      if(input(PIN_B5)==TRUE)
      {
         output_high(PIN_D4);
      }
      else
      {
         output_low(PIN_D4);
      }

      if(input(PIN_B6)==TRUE)
      {
         output_high(PIN_D3);
      }
      else
      {
         output_low(PIN_D3);
      }

      if(input(PIN_B7)==TRUE)
      {
         output_high(PIN_D2);
      }
      else
      {
         output_low(PIN_D2);
      }
   }

   if(input(PIN_B5)==FALSE)                                                       //SI SE CUMPLE LA CONDICIÓN DE QUE EL NIVEL 2 (EL SENSOR DEL NIVEL 2) SEA FALSO, SE
   {                                                                              //EJECUTA LAS SIGUIENTES INSTRUCCIONES CON EVALUACIONES:
      if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI HAY CAMBIO DE NIVELES, SE CUMPLE LA CONDICIÓN
      {                                                                           //Y SE PROCEDE A EJECUTAR LA SIGUIENTE INSTRUCCIÓN
         goto nivel1;                                 //IR AL nivel1 CON LA INSTRUCCIÓN goto nivel1.
      }
      else                                            //SI NO SE CUMPLIÓ, SE PROCEDE A REALIZAR LO QUE DICE EL else
      {
         goto subnivel2;                              //IR AL subnivel2, CON EL FIN DE EVALUAR NUEVAMENTE EL SENSOR DOS
      }                                               //DEBIDO A QUE EL SE REQUIERE LLEGAR AL NIVEL 2 (SENSOR DEL NIVEL 2 [PIN_B5]).
   }
   }
   //FIN DEL NIVEL 2



   //INICIO DEL NIVEL 3
   nivel3:
   if(input(PIN_B2)==TRUE)
   {
      output_low(PIN_D2);                                    //SE ACTIVA LA LUZ DEL NIVEL 2
      output_high(PIN_D3);                                   //SE DESACTIVAN LAS DEMÁS LUCES.
      output_low(PIN_D4);
      output_low(PIN_D5);
      delay_ms(700);                                        //SE RETRASA 700ms Y SE PROCEDE A, APAGAR LA LUZ DEL NIVEL 2
      output_low(PIN_D3);                                   //SE RETRASA 1s MÁS ANTES DE EVALUAR LOS SENSORES.
      delay_ms(500);
      
      subnivel3:
      if(input(PIN_B6)==FALSE)                              //SI NO HAY NADA EN EL SENSOR 2, SE PROCEDE A EJECUTAR LAS SIG. INSTRUCCIONES.
      {
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN.
         {
            while((input(PIN_B6) || input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIOS DE NIVEL...
            {
                                                            //... O SE ENCIENDE EL SENSOR DEL NIVEL 2, BUCLE, HASTA QUE SENSOR DE NIVEL 2 SE ACTIVE.
               output_high(PIN_D0);                         //MIENTRAS NO EXISTA CAMBIO DE NIVEL, SE EMPIEZA A LLENAR EL RECIPIENTE
               output_low(PIN_D1);                          //RECORDAR QUE C7=LLENADO; AQUI SE ENCIENDE EL MOTOR DE LLENADO
                                                            //RECORDAR QUE C6=VACIADO; AQUI SE APAGA EL MOTOR DE VACIADO.

               if(input(PIN_B4)==TRUE)
               {
                  output_high(PIN_D5);
               }
               else
               {
                  output_low(PIN_D5);
               }
   
               if(input(PIN_B5)==TRUE)
               {
                  output_high(PIN_D4);
               }
               else
               {
                  output_low(PIN_D4);
               }
               
               if(input(PIN_B6)==TRUE)
               {
                  output_high(PIN_D3);
               }
               else
               {
                  output_low(PIN_D3);
               }
   
               if(input(PIN_B7)==TRUE)
               {
                  output_high(PIN_D2);
               }
               else
               {
                  output_low(PIN_D2);
               }

            }
            
            if(input(PIN_B4)==TRUE)
            {
               output_high(PIN_D5);
            }
            else
            {
               output_low(PIN_D5);
            }

            if(input(PIN_B5)==TRUE)
            {
               output_high(PIN_D4);
            }
            else
            {
               output_low(PIN_D4);
            }
            
            if(input(PIN_B6)==TRUE)
            {
               output_high(PIN_D3);
            }
            else
            {
               output_low(PIN_D3);
            }

            if(input(PIN_B7)==TRUE)
            {
               output_high(PIN_D2);
            }
            else
            {
               output_low(PIN_D2);
            }
            
            output_low(PIN_D0);                             //SE SALIÓ DEL BUCLE ANTERIOR, ENTONCES SE PROCEDE A, APAGAR LOS MOTORES
            output_low(PIN_D1);                             //Y SE REGRESA AL NIVEL 1. CON ESTO SE VUELVEN A PEDIR LOS DATOS DE NIVEL.
            goto nivel1;
            
         }
         else
         {
            goto nivel1;
         }
      }
      
   if(input(PIN_B7)==TRUE)            //SI HAY AGUA EN LOS NIVELES 3 Y 4, LA CONDICIÓN SE CUMPLE, SINO SE VA AL ELSE.
   {
      while((input(PIN_B6) || input(PIN_B7))==TRUE)  //SI HAY AGUA EN LOS NIVELES 3, 4 Y 5, SE CUMPLE LA...
      {                                                                                //... CONDICIÓN Y SE PROCEDE A VACIAR EL TANQUE.
         output_low(PIN_D0);                             //RECORDAR QUE C7=LLENADO; AQUI SE APAGA EL MOTOR DE LLENADO
         output_high(PIN_D1);                            //RECORDAR QUE C6=VACIADO; AQUI SE ENCIENDE EL MOTOR DE VACIADO.

         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI SE SOLICITA CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN
         {
                                                                 //PARA LA CUAL SE EJECUTA goto nivel1, Y SE VUELVE A EVALUAR LOS NIVELES.
            goto nivel1;                                                               //REGRESA A LA ETIQUETA DE nivel1, (SE SOBREENTIENDE).
         }

         if(input(PIN_B4)==TRUE)
         {
            output_high(PIN_D5);
         }
         else
         {
            output_low(PIN_D5);
         }
   
         if(input(PIN_B5)==TRUE)
         {
            output_high(PIN_D4);
         }
         else
         {
            output_low(PIN_D4);
         }
               
         if(input(PIN_B6)==TRUE)
         {
            output_high(PIN_D3);
         }
         else
         {
            output_low(PIN_D3);
         }

         if(input(PIN_B7)==TRUE)
         {
            output_high(PIN_D2);
         }
         else
         {
            output_low(PIN_D2);
         }

      }

      if(input(PIN_B4)==TRUE)
      {
         output_high(PIN_D5);
      }
      else
      {
         output_low(PIN_D5);
      }

      if(input(PIN_B5)==TRUE)
      {
         output_high(PIN_D4);
      }
      else
      {
         output_low(PIN_D4);
      }

      if(input(PIN_B6)==TRUE)
      {
         output_high(PIN_D3);
      }
      else
      {
         output_low(PIN_D3);
      }

      if(input(PIN_B7)==TRUE)
      {
         output_high(PIN_D2);
      }
      else
      {
         output_low(PIN_D2);
      }
   }

      if(input(PIN_B6)==FALSE)                                                       //SI SE CUMPLE LA CONDICIÓN DE QUE EL NIVEL 2 (EL SENSOR DEL NIVEL 2) SEA FALSO, SE
      {                                                                 //EJECUTA LAS SIGUIENTES INSTRUCCIONES CON EVALUACIONES:
      output_low(PIN_D0);
      output_low(PIN_D1);
      
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI HAY CAMBIO DE NIVELES, SE CUMPLE LA CONDICIÓN
         {                                                                           //Y SE PROCEDE A EJECUTAR LA SIGUIENTE INSTRUCCIÓN
            goto nivel1;                                 //IR AL nivel1 CON LA INSTRUCCIÓN goto nivel1.
         }
         else                                            //SI NO SE CUMPLIÓ, SE PROCEDE A REALIZAR LO QUE DICE EL else
         {
            goto subnivel3;                              //IR AL subnivel2, CON EL FIN DE EVALUAR NUEVAMENTE EL SENSOR DOS
         }                                               //DEBIDO A QUE EL SE REQUIERE LLEGAR AL NIVEL 2 (SENSOR DEL NIVEL 2 [PIN_B5]).
      }
   }

   //FIN DEL NIVEL 3


   //INICIO DEL NIVEL 4
   nivel4:  
   if(input(PIN_B3)==TRUE)       //SI SE ACTIVA EL BOTON DEL NIVEL 2, SE EJECUTAN LAS DEMÁS SENTENCIAS:
   {
      output_high(PIN_D2);                                    //SE ACTIVA LA LUZ DEL NIVEL 2
      output_low(PIN_D3);                                   //SE DESACTIVAN LAS DEMÁS LUCES.
      output_low(PIN_D4);
      output_low(PIN_D5);
      delay_ms(700);                                        //SE RETRASA 700ms Y SE PROCEDE A, APAGAR LA LUZ DEL NIVEL 2
      output_low(PIN_D2);                                   //SE RETRASA 1s MÁS ANTES DE EVALUAR LOS SENSORES.
      delay_ms(500);
      
      if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)     //SI NO HAY INSTRUCCIONES DE CAMBIO DE NIVEL SE CONTINUA,
      {                                                                                //DE LO CONTRARIO, SE PROCEDE A REINICIAR CON EL NIVEL
         goto nivel1;                                                                  //ESPECIFICADO CON EL BOTON CORRESPONDIENTE.
      }
      
      subnivel4:                                            //ETIQUETA PARA ACCEDER CUANDO SE LE NECESITE APARTIR DE ESTA LINEA.
      if(input(PIN_B7)==FALSE)                              //SI NO HAY NADA EN EL SENSOR 2, SE PROCEDE A EJECUTAR LAS SIG. INSTRUCCIONES.
      {
         if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN.
         {
            while((input(PIN_B7) || input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==FALSE) //SI NO HAY CAMBIOS DE NIVEL...
            {                                        //... O SE ENCIENDE EL SENSOR DEL NIVEL 2, BUCLE, HASTA QUE SENSOR DE NIVEL 2 SE ACTIVE.
               output_high(PIN_D0);                         //MIENTRAS NO EXISTA CAMBIO DE NIVEL, SE EMPIEZA A LLENAR EL RECIPIENTE
               output_low(PIN_D1);                          //RECORDAR QUE C7=LLENADO; AQUI SE ENCIENDE EL MOTOR DE LLENADO
                                                           //RECORDAR QUE C6=VACIADO; AQUI SE APAGA EL MOTOR DE VACIADO.
               if(input(PIN_B4)==TRUE)
               {
                  output_high(PIN_D5);
               }
               else
               {
                  output_low(PIN_D5);
               }
   
               if(input(PIN_B5)==TRUE)
               {
                  output_high(PIN_D4);
               }
               else
               {
                  output_low(PIN_D4);
               }
               
               if(input(PIN_B6)==TRUE)
               {
                  output_high(PIN_D3);
               }
               else
               {
                  output_low(PIN_D3);
               }
   
               if(input(PIN_B7)==TRUE)
               {
                  output_high(PIN_D2);
               }
               else
               {
                  output_low(PIN_D2);
               }
            }
            
            if(input(PIN_B4)==TRUE)
            {
               output_high(PIN_D5);
            }
            else
            {
               output_low(PIN_D5);
            }
   
            if(input(PIN_B5)==TRUE)
            {
               output_high(PIN_D4);
            }
            else
            {
               output_low(PIN_D4);
            }
               
            if(input(PIN_B6)==TRUE)
            {
               output_high(PIN_D3);
            }
            else
            {
               output_low(PIN_D3);
            }
   
            if(input(PIN_B7)==TRUE)
            {
               output_high(PIN_D2);
            }
            else
            {
               output_low(PIN_D2);
            }
         
            
            output_low(PIN_D0);                             //SE SALIÓ DEL BUCLE ANTERIOR, ENTONCES SE PROCEDE A, APAGAR LOS MOTORES
            output_low(PIN_D1);                             //Y SE REGRESA AL NIVEL 1. CON ESTO SE VUELVEN A PEDIR LOS DATOS DE NIVEL.
            goto nivel1;
            
         }
         else
         {
            goto nivel1;
         }
      }
      
      while(input(PIN_B7)==TRUE)                                    //SI HAY AGUA EN EL NIVEL 4, LA CONDICIÓN SE CUMPLE, SINO SE VA AL ELSE.
      {
                                                                                         //... CONDICIÓN Y SE PROCEDE A VACIAR EL TANQUE.
            output_low(PIN_D0);                             //RECORDAR QUE C7=LLENADO; AQUI SE APAGA EL MOTOR DE LLENADO
            output_low(PIN_D1);                            //RECORDAR QUE C6=VACIADO; AQUI SE ENCIENDE EL MOTOR DE VACIADO.
            
            if((input(PIN_B0) || input(PIN_B1) || input(PIN_B2) || input(PIN_B3))==TRUE)  //SI SE SOLICITA CAMBIO DE NIVEL, SE CUMPLE LA CONDICIÓN
            {                                                                             //PARA LA CUAL SE EJECUTA goto nivel1, Y SE VUELVE A EVALUAR LOS NIVELES.
               goto nivel1;                                                               //REGRESA A LA ETIQUETA DE nivel1, (SE SOBREENTIENDE).
            }
         

               if(input(PIN_B4)==TRUE)
               {
                  output_high(PIN_D5);
               }
               else
               {
                  output_low(PIN_D5);
               }
   
               if(input(PIN_B5)==TRUE)
               {
                  output_high(PIN_D4);
               }
               else
               {
                  output_low(PIN_D4);
               }
               
               if(input(PIN_B6)==TRUE)
               {
                  output_high(PIN_D3);
               }
               else
               {
                  output_low(PIN_D3);
               }
   
               if(input(PIN_B7)==TRUE)
               {
                  output_high(PIN_D2);
               }
               else
               {
                  output_low(PIN_D2);
               }
         
      }
      goto subnivel4;
   }
   //FIN DEL NIVEL 4
   
   //RA7=lvl_1
   //RA6=lvl_2
   //RA3=lvl_3
   //RA2=lvl_4

            if(input(PIN_B4)==TRUE)
            {
               output_high(PIN_D5);
            }
            else
            {
               output_low(PIN_D5);
            }
   
            if(input(PIN_B5)==TRUE)
            {
               output_high(PIN_D4);
            }
            else
            {
               output_low(PIN_D4);
            }
   
            if(input(PIN_B6)==TRUE)
            {
            output_high(PIN_D3);
            }
            else
            {
               output_low(PIN_D3);
            }
   
            if(input(PIN_B7)==TRUE)
            {
               output_high(PIN_D2);
            }
            else
            {
               output_low(PIN_D2);
            }

   }

      }//FIN DEL WHILE(TRUE), EL CUAL SE REPITE INFINITAMENTE.
   
