
#include "p16f877a.inc"

;   PR2 = 155
;   CCPR1L = 00111110
;   CCPCON1 = 10
;   CCP1CON -> SALIDA RC2
;   PRESCALER = 4
;   TMR2 ON
;   CCP1 = PWM OPERACION
;	PERIODO PWM 100MICROSEGUNDOS

		ORG	0X00
		GOTO	INICIO
	
INICIO
		BSF		STATUS,RP0
		MOVLW	D'155'
		MOVWF	PR2
		BCF		TRISC,2		;RC2 
		BCF		STATUS,RP0
		MOVLW   B'00111110' ;50%DUTYCYCLE
		MOVWF	CCPR1L
		BSF		CCP1CON,5 	; 1 
		BCF		CCP1CON,4	; 0
		BCF		T2CON,1 	;4 PRESCALER
		BSF		T2CON,0
		BSF		T2CON,2		; TMR2 ON
		BSF		CCP1CON,3	; PWM MODE
		BSF		CCP1CON,2
		BSF		CCP1CON,1
		BSF		CCP1CON,0
START
							;ACA NADA BRO POR PONER ALGO PERO EN REALIDAD LA SALIDA DEL PWM ES LO QUE NOS IMPORTA
							;TIPO CONECTARLA A LA BOMBA Y QUE OBVIO DE ALGUN LADO DEFINAMOS COMO VAMOS A APAGAR Y PRENDER LA BOMBA
							;EVIDENTEMENTE ESTO SUCEDERA CUANDO SE LE PIDA ENTONCES SUPONGO QUE CUANDO LA NECESITEMOS PRENDER
							;TENDREMOS POR EJEMPLO UN BTFSC A IR COMPROBANDO MIENTRAS LA NECESITEMOS PRENDIDA Y APENAS NOS MANDEN A APGAR CHAO
		GOTO	START


		END